# Change these first
owner: niebau
repo: https://github.com/niebau/upptime-jundj

sites:
  - name: Gartenallerlei
    url: https://gartenallerlei.de
  - name: Rollibeet
    url: https://rollibeet.de
  - name: Lumodomo
    url: https://lumodomo.de
  - name: SPIKA
    url: https://www.spika-spiele.de
  - name: Handelsgut
    url: https://www.handelsgut.net
  - name: Test Broken Site
    url: https://googleisevil.hehe

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-jundj
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
